# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Brian J Bohman, PhD"
email: "brianbohman@gmail.com"
description: "Personal website for Brian J. Bohman"
twitter_username: "bjbohman"
github_username: "bohm0072"
minimal_mistakes_skin: default #contrast
search: true
url: "https://brianjbohman.com"
repository: "bohm0072/bohm0072.github.io"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Chicago # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Brian J Bohman, PhD"
  avatar : "/assets/images/Headshot.jpg"
  bio    : "Delivering Data-Driven Solutions for Agronomists, Researchers, and the Food + Ag Value Chain."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bjbohman/"
    - label: "Google Scholar"
      icon: "ai ai-fw ai-google-scholar-square"
      url: "https://scholar.google.com/citations?hl=en&user=e8xG8uAAAAAJ"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bohm0072"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bjbohman"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:brianbohman@gmail.com"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bjbohman/"
    - label: "Google Scholar"
      icon: "ai ai-fw ai-google-scholar-square"
      url: "https://scholar.google.com/citations?hl=en&user=e8xG8uAAAAAJ"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bohm0072"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bjbohman"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:brianbohman@gmail.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
